# BlitzSsentials Config!

# -----------------------------------------------------------
# Config Notes:

# Use & for color codes! (Search 'MC Code codes' in a browser if you don't know what it is)
# Use \n for Enter/Another Line
# Remember the: Quotations ("<Message>")

# MAIN/GENERAL CONFIG

launchpad:
  enable-launchpad: false
# Make sure that the block is valid (Use block item ID or /give to find/get your block)
  top-block: "heavy_weighted_pressure_plate"
  bottom-block: "redstone_block"
# Play Sounds to make the Launchpad feel more Dynamic
# Make sure that the sound is valid! (use /playsound to test and/or find sounds)
  sound-1:
    sound: "block.piston.extend"
    volume: 2
    pitch: 1
  sound-2:
    sound: "block.piston.contract"
    volume: 2
    pitch: 1
# Set Particle for Visuals
# Make sure that the particle is valid! (use /particle to test and/find particles)
  particle:
    particle: "cloud"
    count: 20
# Set Launch Power (XZ is direction, foward, backwards, left, right, and Y is height, Up)
  Y-launch: 1
  launch-delay: 5
  XZ-launch: 2

# Broadcast a Countdown to the whole Server or get Personal messages of a Countdown!
countdown:
  personal:
    enable-prefix: true
    prefix: "&8[&7Personal Countdown&8] &r"
    end-message: "&cPersonal Countdown Ended!"
  bc:
    enable-prefix: true
    prefix: "&8[&7Countdown&8] &r"
    end-message: "&8[&7Countdown&8] &cCountdown Ended!"
    
# Broadcast or Alert Messages to the whole Server!
broadcast:
  bc-server:
    enable-prefix: true
    prefix: "&7[&cBroadcast&7] &r"
  bc-alert:
    enable-prefix: true
    prefix: "&8[&4ALERT&8] &r"
# Make sure that the sound is valid! (use /playsound to test and/or find sounds)
    enable-sound: true
    sound: "block.anvil.land"
    volume: 2
    pitch: -10

prefix-addon:
# Add a prefix to addon to Blitzssentials (ex: [ServerName Blitzssentials])
  enable-addon: false
  prefix: "&8ServerName"

# -----------------------------------------------------------
# END OF MAIN/GENERAL CONFIG
# -----------------------------------------------------------
# COMMANDS CONFIG

mass-summon:
  enable-max-amount: false
  max-amount: 100

# -----------------------------------------------------------
# END OF COMMANDS CONFIG
# -----------------------------------------------------------
# GAMEPLAY CONFIG

#Allows a player to Sneak-Right-Click a EXP Bottle to collect EXP directly.
enable-sneak-exp: false



# -----------------------------------------------------------
# END OF GAMEPLAY CONFIG
# -----------------------------------------------------------
# JOIN/LEAVE CONFIG

join-position:
  enable-join-position: false
# Specify which world
  world: "world"
# Make sure that Coordinates are Correct (Use /tp to test)
  x: 0
  y: 64
  z: 0
  pitch: 0
  yaw: 0

# When someone joins, they hear a sound!
# Make sure that the sound is valid! (use /playsound to test and/or find sounds)
# NOTE: (For Music Discs and Game MUSIC, pitch adjusts the Speed)
join-sound:
  enable-join-sound: true
  sound: "entity.player.levelup"
  volume: 2
  pitch: 0
  
# PLACEHOLDERS: (For Join/Leave Config)
# Use %player% for Playername
# Use %line% for Line
# Use %plugin% for Plugin and Plugin Version (Admin Only)
# Use %api% for Plugin's Spigot API and Dependencies (Admin Only)

# NOTES: (For Join/Leave Config)
# The Order of Messages is: Default-Personal, then Admin-Personal (If they have the permission), and last, Global
    
join-message:
# Default Personal Message (Only users with the permission BlitzSsentials.join (default) can see this only, when they join)
  default-personal:
    enable-default-personal: true
    default-personal-message: "&6%line%\n&b[&3BZSs&b] &aWelcome, &l%player%!\n&6%line%"
    
# Admin Personal Message (Only users with the permission BlitzSsentials.adminjoin can see this only, when they join)
  admin-personal:
    enable-admin-personal: true
    admin-personal-message: "&bWelcome Admin/Operator!\n&r%plugin% - %api%\n&6%line%"
    
# Global Message (Everyone sees this when someone Joins)
  global:
    enable-global: true
    global-message: "&aWelcome &l%player% &ato the Server Everyone!"

leave-message: 
# Leave Message (Everyone sees this when someone Leaves)
  leave:
    enable-leave-message: true
    leave-message: "&eSay Goodbye to &l%player% &eEveryone!"
    
# -----------------------------------------------------------
# END OF JOIN/LEAVE CONFIG
# -----------------------------------------------------------
# BETA CONFIG

# WARNING: All these features are in BETA, may not work, and/or may crash your server | Disabled on Default
old-pvp:
  enable-old-pvp: false

# -----------------------------------------------------------
# END OF BETA CONFIG
# -----------------------------------------------------------
# More to be added!

# -----------------------------------------------------------
# End of the line... Literally
# DO NOT CHANGE THIS!
config-version: 000400