name: BlitzSsentials
version: 1.0.0
author: BlitzTDM
main: net.tydiumcraft.Blitzssentials.Main
description: The TydiumCraft Hi Plugin

commands:
  hi:
    aliases: [hello]
    description: The Hi Command
