name: BlitzSsentials
version: 1.0.0
author: BlitzTDM
main: net.tydiumcraft.Blitzssentials.Main
description: The BlitzSsentials Plugin that is also ran on TydiumCraft

commands:
  Test:
    aliases: [tst]
    description: The Test Command
