# BlitzSsentials Config!

# -----------------------------------------------------------
# MAIN/GENERAL CONFIG

launchpad:
  enable-launchpad: false
# Make sure that the block is valid (Use block item ID or /give to find/get your block)
  top-block: "heavy_weighted_pressure_plate"
  bottom-block: "redstone_block"
# Play Sounds to make the Launchpad feel more Dynamic
# Make sure that the sound is valid! (use /playsound to test and/or find sounds)
  sound-1:
    sound: "block.piston.extend"
    volume: 2
    pitch: 1
  sound-2:
    sound: "block.piston.contract"
    volume: 2
    pitch: 1
# Set Particle for Visuals
# Make sure that the particle is valid! (use /particle to test and/find particles)
  particle:
    particle: "cloud"
    count: 20
# Set Launch Power (XZ is direction, foward, backwards, left, right, and Y is height, Up)
  Y-launch: 1
  launch-delay: 5
  XZ-launch: 2

# -----------------------------------------------------------
# END OF MAIN/GENERAL CONFIG
# -----------------------------------------------------------
# COMMANDS CONFIG

mass-summon:
  enable-max-amount: false
  max-amount: 100

# -----------------------------------------------------------
# END OF COMMANDS CONFIG
# -----------------------------------------------------------
# JOIN/LEAVE CONFIG

# When someone joins, they hear a sound!
# Make sure that the sound is valid! (use /playsound to test and/or find sounds)
join-sound:
  enable-join-sound: true
  sound: "entity.player.levelup"
  volume: 2
  pitch: 0
  
# PLACEHOLDERS:
# Use %player% for Playername
# Use %line% for Line
# Use %plugin% for Plugin and Plugin Version (Admin Only)
# Use %api% for Plugin's Spigot API and Dependencies (Admin Only)
# Use & for color codes!
# Use \n for Enter/Another Line

# NOTES:
# Remember the: Quotations ("<Mesaage>")
# The Order of Messages is: Default-Personal, then Admin-Personal (If they have the permission), and last, Global
    
join-message:
# Default Personal Message (Only users with the permission BlitzSsentials.join (default) can see this only, when they join)
  default-personal:
    enable-default-personal: true
    default-personal-message: "&6%line%\n&b[&3BZSs&b] &aWelcome, &l%player%!\n&6%line%"
    
# Admin Personal Message (Only users with the permission BlitzSsentials.adminjoin can see this only, when they join)
  admin-personal:
    enable-admin-personal: true
    admin-personal-message: "&bWelcome Admin/Operator!\n&r%plugin% - %api%\n&6%line%"
    
# Global Message (Everyone sees this when someone Joins)
  global:
    enable-global: true
    global-message: "&aWelcome &l%player% &ato the Server Everyone!"

leave-message: 
# Leave Message (Everyone sees this when someone Leaves)
  leave:
    enable-leave-message: true
    leave-message: "&eSay Goodbye to &l%player% &eEveryone!"
    
# -----------------------------------------------------------
# END OF JOIN/LEAVE CONFIG
# -----------------------------------------------------------
# More to be added!

# -----------------------------------------------------------
# End of the line... Literally
# DO NOT CHANGE THIS!
config-version: 000200